# Generated by Django 4.0.5 on 2022-07-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desig', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='cv')),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(blank=True)),
                ('skill1', models.CharField(max_length=100)),
                ('s_percent1', models.IntegerField(verbose_name=range(1, 100))),
                ('skill2', models.CharField(blank=True, max_length=100)),
                ('s_percent2', models.IntegerField(verbose_name=range(1, 100))),
                ('skill3', models.CharField(blank=True, max_length=100)),
                ('s_percent3', models.IntegerField(blank=True, null=True, verbose_name=range(1, 100))),
                ('skill4', models.CharField(blank=True, max_length=100)),
                ('s_percent4', models.IntegerField(blank=True, null=True, verbose_name=range(1, 100))),
                ('language1', models.CharField(max_length=100)),
                ('l_percent1', models.IntegerField(verbose_name=range(1, 100))),
                ('language2', models.CharField(blank=True, max_length=100)),
                ('l_percent2', models.IntegerField(verbose_name=range(1, 100))),
                ('language3', models.CharField(blank=True, max_length=100)),
                ('l_percent3', models.IntegerField(blank=True, null=True, verbose_name=range(1, 100))),
                ('work1', models.CharField(max_length=100)),
                ('work1_s', models.DateField()),
                ('work1_e', models.DateField()),
                ('work1_des', models.TextField(blank=True)),
                ('work2', models.CharField(blank=True, max_length=100)),
                ('work2_s', models.DateField(blank=True, null=True)),
                ('work2_e', models.DateField(blank=True, null=True)),
                ('work2_des', models.TextField(blank=True)),
                ('work3', models.CharField(blank=True, max_length=100)),
                ('work3_s', models.DateField(blank=True, null=True)),
                ('work3_e', models.DateField(blank=True, null=True)),
                ('work3_des', models.TextField(blank=True)),
                ('edu1', models.CharField(max_length=100)),
                ('edu1_s', models.DateField()),
                ('edu1_e', models.DateField()),
                ('edu1_des', models.TextField(blank=True)),
                ('edu2', models.CharField(max_length=100)),
                ('edu2_s', models.DateField()),
                ('edu2_e', models.DateField()),
                ('edu2_des', models.TextField(blank=True)),
                ('edu3', models.CharField(blank=True, max_length=100)),
                ('edu3_s', models.DateField(blank=True, null=True)),
                ('edu3_e', models.DateField(blank=True, null=True)),
                ('edu3_des', models.TextField(blank=True)),
                ('fb', models.URLField(blank=True, max_length=250)),
                ('insta', models.URLField(blank=True, max_length=250)),
                ('linkdin', models.URLField(blank=True, max_length=250)),
            ],
        ),
    ]
