# Generated by Django 4.0.5 on 2022-07-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='desig',
            new_name='designation',
        ),
    ]
