from django import forms

from Cv_app.models import Cv


class CvForm(forms.ModelForm):
    class Meta:
        model = Cv
        fields = '__all__'
        labels = {
            'name': 'Enter your name :',
            'designation': 'Enter your designation :',
            'image': 'Upload your image of size 512x512px :',
            'address': 'Your home address :',
            'email': 'Mail ID :',
            'phone': "Whatsapp Number :",
            'skill1': 'Skill 1 :',
            's_percent1': 'Level of knowledge in skill 1 :',
            'skill2': 'Skill 2 :',
            's_percent2': 'Level of knowledge in skill 2 :',
            'skill3': 'Skill 3 :',
            's_percent3': 'Level of knowledge in skill 3 :',
            'skill4': 'Skill 4 :',
            's_percent4': 'Level of knowledge in skill 4 :',
            'language1': 'Language 1',
            'l_percent1': 'Proficiency in Language 1 :',
            'language2': 'Language 2',
            'l_percent2': 'Proficiency in Language 2 :',
            'language3': 'Language 3',
            'l_percent3': 'Proficiency in Language 3 :',
            'work1': 'Work Experience 1 :',
            'work1_s': 'Work 1 Start :',
            'work1_e': 'Work 1 End :',
            'work1_des': 'Description about work 1',
            'work2': 'Work Experience 2 :',
            'work2_s': 'Work 2 Start :',
            'work2_e': 'Work 2 End :',
            'work2_des': 'Description about work 2',
            'work3': 'Work Experience 3 :',
            'work3_s': 'Work 3 Start :',
            'work3_e': 'Work 3 End :',
            'work3_des': 'Description about work 3',
            'edu1': 'Enter your qualification :',
            'edu1_s': 'Start :',
            'edu1_e': 'End :',
            'edu1_des': 'Description :',
            'edu2': 'Education 2 :',
            'edu2_s': 'Start :',
            'edu2_e': 'End :',
            'edu2_des': 'Description :',
            'edu3': 'Education 3 :',
            'edu3_s': 'Start :',
            'edu3_e': 'End :',
            'edu3_des': 'Description :',
            'fb': 'Your Facebook profile :',
            'insta': 'Your Insta profile :',
            'linkdin': 'Your LinkedIn profile :',

        }
        widgets = {
            'work1_s': forms.DateInput(format=('%d/%m/%Y'),
                                       attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                              'type': 'date'}),
            'work1_e': forms.DateInput(format=('%d/%m/%Y'),
                                       attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                              'type': 'date'}),
            'work2_s': forms.DateInput(format=('%d/%m/%Y'),
                                       attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                              'type': 'date'}),
            'work2_e': forms.DateInput(format=('%d/%m/%Y'),
                                       attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                              'type': 'date'}),
            'work3_s': forms.DateInput(format=('%d/%m/%Y'),
                                       attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                              'type': 'date'}),
            'work3_e': forms.DateInput(format=('%d/%m/%Y'),
                                       attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                              'type': 'date'}),
            'edu1_s': forms.DateInput(format=('%d/%m/%Y'),
                                      attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                             'type': 'date'}),
            'edu1_e': forms.DateInput(format=('%d/%m/%Y'),
                                      attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                             'type': 'date'}),
            'edu2_s': forms.DateInput(format=('%d/%m/%Y'),
                                      attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                             'type': 'date'}),
            'edu2_e': forms.DateInput(format=('%d/%m/%Y'),
                                      attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                             'type': 'date'}),
            'edu3_s': forms.DateInput(format=('%d/%m/%Y'),
                                      attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                             'type': 'date'}),
            'edu3_e': forms.DateInput(format=('%d/%m/%Y'),
                                      attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                             'type': 'date'}),
            's_percent1': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'In percentage (eg:87)'}),
            's_percent2': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'In percentage (eg:87)'}),
            's_percent3': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'In percentage (eg:87)'}),
            's_percent4': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'In percentage (eg:87)'}),
            'l_percent1': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'In percentage (eg:87)'}),
            'l_percent2': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'In percentage (eg:87)'}),
            'l_percent3': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'In percentage (eg:87)'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'placeholder': 'submit image'}),
            'designation': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.NumberInput(attrs={'class': 'form-control'}),
            'skill1': forms.TextInput(attrs={'class': 'form-control'}),
            'skill2': forms.TextInput(attrs={'class': 'form-control'}),
            'skill3': forms.TextInput(attrs={'class': 'form-control'}),
            'skill4': forms.TextInput(attrs={'class': 'form-control'}),
            'language1': forms.TextInput(attrs={'class': 'form-control'}),
            'language2': forms.TextInput(attrs={'class': 'form-control'}),
            'language3': forms.TextInput(attrs={'class': 'form-control'}),
            'edu1': forms.TextInput(attrs={'class': 'form-control'}),
            'edu1_des': forms.TextInput(attrs={'class': 'form-control'}),
            'edu2': forms.TextInput(attrs={'class': 'form-control'}),
            'edu2_des': forms.TextInput(attrs={'class': 'form-control'}),
            'edu3': forms.TextInput(attrs={'class': 'form-control'}),
            'edu3_des': forms.TextInput(attrs={'class': 'form-control'}),
            'work1': forms.TextInput(attrs={'class': 'form-control'}),
            'work1_des': forms.Textarea(attrs={'class': 'form-control'}),
            'work2': forms.TextInput(attrs={'class': 'form-control'}),
            'work2_des': forms.Textarea(attrs={'class': 'form-control'}),
            'work3': forms.TextInput(attrs={'class': 'form-control'}),
            'work3_des': forms.Textarea(attrs={'class': 'form-control'}),
            'fb': forms.URLInput(attrs={'class': 'form-control'}),
            'insta': forms.URLInput(attrs={'class': 'form-control'}),
            'linkdin': forms.URLInput(attrs={'class': 'form-control'}),
        }
